version: '3.8'
services:
  web:
    build: .
    container_name: web
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - db
    command: >
      sh -c "
      uvicorn app.app:app --host 0.0.0.0 --port 8000 &
      celery -A app.celery.celery worker --loglevel=info
      "

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  db:
    image: postgres:14
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
